INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (52, '管理员管理', 1, '', '', 0, 100, '管理员管理', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (53, '角色管理', 1, '', '', 0, 100, '角色管理', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (54, '管理员管理', 2, '管理员列表', 'manager', 52, 100, '管理员列表', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (55, '管理员管理', 2, '增加管理员', 'manager/add', 52, 100, '管理员列表', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (56, '管理员管理', 3, '编辑管理员', 'manager/edit', 52, 100, '编辑管理员123456', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (57, '管理员管理', 3, '删除管理员', 'manager/delete', 52, 100, '删除管理员', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (59, '角色管理', 2, '角色列表', 'role', 53, 100, '角色列表', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (60, '角色管理', 2, '增加角色', 'role/add', 53, 100, '增加角色', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (61, '角色管理', 3, '编辑角色', 'role/edit', 53, 100, '编辑角色', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (62, '角色管理', 3, '删除角色', 'role/delete', 53, 100, '删除角色', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (63, '权限管理', 1, '', '', 0, 100, '权限管理', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (64, '权限管理', 2, '权限列表', 'access', 63, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (67, '权限管理', 2, '增加权限', 'access/add', 63, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (68, '轮播图管理', 1, '', '', 0, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (69, '轮播图管理', 2, '轮播图列表', 'focus', 68, 101, '1111', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (70, '轮播图管理', 2, '增加轮播图', 'focus/add', 68, 100, '增加轮播图', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (71, '轮播图管理', 3, '编辑轮播图', 'focus/edit', 68, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (75, '轮播图管理', 3, '删除轮播图', 'focus/delete', 68, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (76, '管理员管理', 3, '执行增加管理员', 'manager/doAdd', 52, 100, '执行增加', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (77, '管理员管理', 3, '执行修改管理员', 'manager/doEdit', 52, 100, '执行修改', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (78, '角色管理', 3, '执行增加角色', 'role/doAdd', 53, 100, '执行增加', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (79, '角色管理', 3, '执行修改角色', 'role/doEdit', 53, 100, '执行修改', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (80, '角色管理', 3, '角色授权', 'role/auth', 53, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (81, '角色管理', 3, '执行角色授权', 'role/doAuth', 53, 100, '执行授权', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (82, '权限管理', 3, '修改权限', 'access/edit', 63, 100, '执行修改', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (83, '权限管理', 3, '删除权限', 'access/delete', 63, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (84, '权限管理', 3, '执行增加权限', 'access/doAdd', 63, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (85, '权限管理', 3, '执行修改权限', 'access/doEdit', 63, 100, '执行修改
', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (86, '轮播图管理', 3, '执行增加', 'focus/doAdd', 68, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (87, '商品管理', 1, '', '', 0, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (88, '商品管理', 2, '商品分类', 'goodsCate', 88, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (89, '商品管理', 3, '增加商品分类', 'goodsCate/add', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (90, '商品管理', 3, '执行增加商品分类', 'goodsCate/doAdd', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (91, '商品管理', 3, '修改商品分类', 'goodsCate/edit', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (92, '商品管理', 3, '执行修改商品分类', 'goodsCate/doEdit', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (93, '商品管理', 3, '删除商品分类', 'goodsCate/delete', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (94, '商品管理', 2, '商品类型列表', 'goodsType', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (95, '商品管理', 3, '增加商品类型', 'goodsType/add', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (96, '商品管理', 3, '编辑商品类型', 'goodsType/edit', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (97, '商品管理', 3, '执行增加 商品类型', 'goodsType/doAdd', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (98, '商品管理', 3, '执行修改 商品类型', 'goodsType/doEdit', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (99, '商品管理', 3, '删除 商品类型', 'goodsType/delete', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (100, '商品管理', 2, '商品分类列表', 'goodsCate', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (101, '商品管理', 2, '商品列表', 'goods', 87, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (102, '系统设置', 1, '', '', 0, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (103, '导航管理', 2, '导航首页', 'nav', 102, 100, '', 0, 1);
INSERT INTO shop.access (id, module_name, type, action_name, url, module_id, sort, description, add_time, status) VALUES (104, '商店设置', 2, '商店设置', 'setting', 102, 100, '', 0, 1);
